---
  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/andruf1
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: qwerty
    jpa:
      hibernate:
        ddl-auto: update

